services:
  pdf-chat-api:
    build: .
    container_name: pdf-chat-api
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount PDF folder for easy file management
      - ./pdf:/app/pdf
      # Mount tmp folder for persistent vector database
      - pdf_vector_db:/app/tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - pdf-chat-network

volumes:
  pdf_vector_db:
    driver: local

networks:
  pdf-chat-network:
    driver: bridge 